title = "My favorite AI papers of 2023: a deep dive"
date = "January 3rd, 2024"
subtitle = "A look back on the past year. Here are my favorite papers that I hope can capture some of the weirdness of machine learning and AI of 2023!"
link = "/blog/ai-2023"