title = "An Ensembled Encoder-Decoder System for Interlinear Glossed Text"
authors = "**Edith Coates**"
venue = "Proceedings of the 20th SIGMORPHON workshop on Computational Research in Phonetics, Phonology, and Morphology"
link = "https://aclanthology.org/2023.sigmorphon-1.23/"