title = "Dim Wihl Gat Tun: The Case for Linguistic Expertise in NLP for Under-Documented Languages"
authors = "Clarissa Forbes, Farhan Samir, Bruce Oliver, Changbing Yang, **Edith Coates**, Garrett Nicolai, Miikka Silfverberg"
venue = "Findings of the Association for Computational Linguistics: ACL 2022"
link = "https://aclanthology.org/2022.findings-acl.167/"