title = "Expanding the JHU Bible Corpus for Machine Translation of the Indigenous Languages of North America"
authors = "Garrett Nicolai, **Edith Coates**, Ming Zhang, Miikka Silfverberg"
venue = "Proceedings of the 4th Workshop on the Use of Computational Methods in the Study of Endangered Languages Volume 1 (Papers)"
link = "https://aclanthology.org/2021.computel-1.1/"