title = "An Inflectional Database for Gitksan"
authors = "Bruce Oliver, Clarissa Forbes, Farhan Samir, Changbing Yang, **Edith Coates**, Garrett Nicolai, Miikka Silfverberg"
venue = "Proceedings of the Thirteenth Language Resources and Evaluation Conference"
link = "https://aclanthology.org/2022.lrec-1.710/"